### ISSUE TITLE
Issue with FitPredictClassifier

### ISSUE THREAD

**Issue by AshCher51** [oulenz/fuzzy-rough-learn#4]
When trying to use the FitPredictClassifier and applying the fit function as follows:

**import numpy as np
import pandas as pd
import frlearn
from frlearn.ensembles import FRNN
from frlearn.base import FitPredictClassifier
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
filepath = '/Users/aashish/Desktop/wpbc.csv'
prog = pd.read_csv(filepath)
X = prog.drop('y', axis=1)
y = prog.y
from sklearn.model_selection import train_test_split
X_train, y_train, X_test, y_test = train_test_split(X,y,test_size = 0.2)
frnn = FitPredictClassifier(FRNN)
frnn.fit(X_train, y_train)
frnn.predict(X_test)**

I am receiving an error with the fit function, as follows
TypeError: '(array([ 1,  2,  4, 10, 11, 12, 13, 14, 16, 19, 22, 24, 25, 26, 27, 28, 31,
       32, 36, 38]), array([33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       33, 33, 33]))' is an invalid key

Please help me out with this error.

**Comment by oulenz** [comment]
It seems you've got the order of the return values of `train_test_split` mixed up, that should be:

`X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)`

(BTW: I've moved FRNN from `ensembles` to `neighbours`, so if in the future you pull from master, you'll have to change that import accordingly.)

**Comment by oulenz** [comment]
Btw, sorry I didn't see your earlier issues, I had forgot to turn on notifications. If you run into any future issues, let me know!
