### ISSUE TITLE
Issues with FRNN

### ISSUE THREAD

**Issue by hoangdv-uet** [oulenz/fuzzy-rough-learn#5]
First, I want to thanks oulenz for contribution in Fuzzy-rough-learn
- I found the problem with digits dataset (sk-learn) that when using FRNN classifier, all the values when query in testset is 0.5. 
that lead to the whole prediction is one class. Eg:
array([[0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       ...,
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5]])
- Other problem is in FRFS. Look like that the soft_min() funtion is not updated for argument "k" in frlearn.neighbours - FRFS

Can we discuss more about 2 problems above?
My email is ca.hoanguet@gmail.com
That would be great if we have detail in fuzzy-rough-learn
once again, thank you so much for your contribution.

Hoang.

**Comment by oulenz** [comment]
Hi, I'm happy that you are giving fuzzy-rough-learn a try!

1. The reason is that the FRNN class truncates all distances greater than 1 — you first have to scale all values down to ~ [0, 1]. The reasoning behind leaving this for the user was that people might want to scale in different ways.
However, I agree that this is confusing, so I've now built in scaling.

2. I am sorry about that! In fact, I fixed this last week.

Could you try again with the lastest version of the master branch?

**Comment by hoangdv-uet** [comment]
Thank you that had a true prediction.
I want to ask about the FRSF to reduce the dimension of the digit data. But
i don't now the output is nothing, i scale all values to [0,1] by the way
Here is my code:
[image: image.png]

Vào Th 3, 11 thg 8, 2020 vào lúc 20:32 Oliver Urs Lenz <
notifications@github.com> đã viết:

**Comment by oulenz** [comment]
I'm not quite sure what you mean— how many features are you left with?

(I can't see the picture you attached, could you copy your code as text?)

**Comment by hoangdv-uet** [comment]
Yes,
this i my code:
from frlearn.neighbours import FRFS
preprocessor = FRFS()
X_FRPS, y_FRPS = preprocessor.process(X2, y)
X_FRPS
>>> array([], shape=(1797, 0), dtype=float64)

X2 is data training from load_digits (sklearn) and y is its labels

Vào Th 4, 12 thg 8, 2020 vào lúc 19:40 Oliver Urs Lenz <
notifications@github.com> đã viết:

**Comment by oulenz** [comment]
The problem was that some attributes in this dataset are constant, so when dividing by the range these attributes became infinite. I have fixed this now.
